//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseData
    {
        public BaseData()
        {
            this.UserAuthor = new HashSet<UserAuthor>();
        }
    
        public int ID { get; set; }
        public int ParentId { get; set; }
        public string TypeName { get; set; }
        public string TypeText { get; set; }
    
        public virtual ICollection<UserAuthor> UserAuthor { get; set; }
    }
}
